"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/app/store";
import { fetchPosts } from "./features/posts/postsSlice";
import { fetchUsers } from "./features/users/usersSlice";
import Header from "./components/Header";


store.dispatch(fetchUsers());
store.dispatch(fetchPosts());

const inter = Inter({ subsets: ["latin"] });

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>

        <body className={inter.className}>
          <Header />
          {children}

        </body>
      </Provider>
    </html>
  );
}
